### ISSUE TITLE
brandLogo on android does not show anything

### ISSUE THREAD

**Issue by Prakosa** [stripe/stripe-identity-react-native#100]
Hi All, 

I am using this SDK and all is working as expected, except the brandLogo in Android does not show anything.

in iOS it show as expected but on android it does not show anything.

brandLogo: Image.resolveAssetSource(images.brandIcon)

the format of brandIcon is png.

This is the crashlog from logcat in Android Studio.

<img width="1339" alt="Screen Shot 2566-02-24 at 16 45 48" src="https://user-images.githubusercontent.com/30237000/221148066-c206d2fd-66df-48db-a6de-845535896280.png">

it should working same as iOS.

please help me to solve this issue. thanks

**Comment by ccen-stripe** [comment]
Hi @Prakosa, sorry for the delay but we just fixed this in https://github.com/stripe/stripe-android/pull/6341, the Android release should be out on Monday, 13, 2023. Updating to the latest [0.1.4](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.1.4) by then should resolve this issue. Thanks!

**Comment by Prakosa** [comment]
Hi @ccen-stripe thanks for the update before. Unfortunately it still does not work when the app is build for release. It still does not show the logo you can check it by yourself. https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.1.5 I even update the library but it still does not show the logo in release build.

**Comment by Prakosa** [comment]
Once again sorry, can you make the logo are center. Thanks @ccen-stripe 
![IMG_5158](https://user-images.githubusercontent.com/30237000/232965416-c603e9ec-89b3-4f17-aa33-133dcf7f75ac.jpg)

**Comment by ccen-stripe** [comment]
hi @Prakosa it seems the logo does show up, could you verify if this is a false alarm? ([This](https://github.com/stripe/stripe-android/pull/6341) is the fix on Android SDK ICYMI)

Re. center the image - We follow material design guidelines for our Android SDK to left align the title and icons, this is different on on iOS SDKs where they are centered aligned

**Comment by ccen-stripe** [comment]
feel free to reopen if it still persists
